// src/themes.js

export const THEMES = [
    {
        name: 'Galaxy Night',
        background: 'bg-zinc-950',
        text: 'text-zinc-100',
        primary: 'bg-indigo-600',
        primaryHover: 'bg-indigo-700',
        secondary: 'bg-purple-700',
        secondaryHover: 'bg-purple-800',
        cardBg: 'bg-zinc-900',
        cardText: 'text-zinc-300',
        border: 'border-zinc-700',
        buttonPrimary: 'bg-indigo-600',
        buttonPrimaryHover: 'bg-indigo-700',
        buttonText: 'text-white',
        highlight: 'text-purple-400',
        highlightSecondary: 'text-indigo-400',
        highlightTertiary: 'text-cyan-400',
        successColor: 'text-emerald-400',
        warningColor: 'text-amber-400',
        errorColor: 'text-rose-400',
        infoColor: 'text-sky-400',
        iconBg: 'bg-purple-600/10',
        gradientFrom: 'from-zinc-950',
        gradientTo: 'to-indigo-950',
        isPremium: false,
    },
    {
        name: 'Volcano Ash',
        background: 'bg-gray-900',
        text: 'text-gray-100',
        primary: 'bg-red-700',
        primaryHover: 'bg-red-800',
        secondary: 'bg-orange-600',
        secondaryHover: 'bg-orange-700',
        cardBg: 'bg-gray-800',
        cardText: 'text-gray-300',
        border: 'border-gray-700',
        buttonPrimary: 'bg-red-700',
        buttonPrimaryHover: 'bg-red-800',
        buttonText: 'text-white',
        highlight: 'text-red-500',
        highlightSecondary: 'text-orange-400',
        highlightTertiary: 'text-amber-300',
        successColor: 'text-lime-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-blue-400',
        iconBg: 'bg-red-700/10',
        gradientFrom: 'from-gray-900',
        gradientTo: 'to-black',
        isPremium: false,
    },
    {
        name: 'Regal Purple',
        background: 'bg-purple-950',
        text: 'text-purple-100',
        primary: 'bg-amber-400',
        primaryHover: 'bg-amber-300',
        secondary: 'bg-yellow-300',
        secondaryHover: 'bg-yellow-200',
        cardBg: 'bg-purple-900',
        cardText: 'text-purple-200',
        border: 'border-purple-800',
        buttonPrimary: 'bg-amber-400',
        buttonPrimaryHover: 'bg-amber-300',
        buttonText: 'text-purple-950',
        highlight: 'text-amber-300',
        highlightSecondary: 'text-yellow-200',
        highlightTertiary: 'text-fuchsia-400',
        successColor: 'text-emerald-300',
        warningColor: 'text-orange-300',
        errorColor: 'text-pink-400',
        infoColor: 'text-indigo-300',
        iconBg: 'bg-amber-400/10',
        gradientFrom: 'from-purple-950',
        gradientTo: 'to-violet-950',
        isPremium: true,
    },
    {
        name: 'Graphite Slate',
        background: 'bg-slate-800',
        text: 'text-slate-100',
        primary: 'bg-indigo-500',
        primaryHover: 'bg-indigo-600',
        secondary: 'bg-blue-600',
        secondaryHover: 'bg-blue-700',
        cardBg: 'bg-slate-700',
        cardText: 'text-slate-300',
        border: 'border-slate-600',
        buttonPrimary: 'bg-indigo-500',
        buttonPrimaryHover: 'bg-indigo-600',
        buttonText: 'text-white',
        highlight: 'text-indigo-400',
        highlightSecondary: 'text-blue-400',
        highlightTertiary: 'text-cyan-400',
        successColor: 'text-green-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-sky-400',
        iconBg: 'bg-indigo-500/10',
        gradientFrom: 'from-slate-800',
        gradientTo: 'to-gray-900',
        isPremium: true, // Now premium
    },
    {
        name: 'Modern Dark',
        background: 'bg-neutral-900',
        text: 'text-neutral-50',
        primary: 'bg-blue-600',
        primaryHover: 'bg-blue-700',
        secondary: 'bg-sky-500',
        secondaryHover: 'bg-sky-600',
        cardBg: 'bg-neutral-800',
        cardText: 'text-neutral-200',
        border: 'border-neutral-700',
        buttonPrimary: 'bg-blue-600',
        buttonPrimaryHover: 'bg-blue-700',
        buttonText: 'text-white',
        highlight: 'text-blue-400',
        highlightSecondary: 'text-sky-300',
        highlightTertiary: 'text-teal-300',
        successColor: 'text-emerald-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-blue-400',
        iconBg: 'bg-blue-600/10',
        gradientFrom: 'from-neutral-900',
        gradientTo: 'to-gray-900',
        isPremium: true, // Now premium
    },
    {
        name: 'Forest Shadows',
        background: 'bg-green-950',
        text: 'text-green-100',
        primary: 'bg-emerald-600',
        primaryHover: 'bg-emerald-700',
        secondary: 'bg-teal-600',
        secondaryHover: 'bg-teal-700',
        cardBg: 'bg-green-900',
        cardText: 'text-green-200',
        border: 'border-green-800',
        buttonPrimary: 'bg-emerald-600',
        buttonPrimaryHover: 'bg-emerald-700',
        buttonText: 'text-white',
        highlight: 'text-emerald-400',
        highlightSecondary: 'text-teal-400',
        highlightTertiary: 'text-lime-400',
        successColor: 'text-lime-400',
        warningColor: 'text-amber-400',
        errorColor: 'text-red-400',
        infoColor: 'text-cyan-400',
        iconBg: 'bg-emerald-600/10',
        gradientFrom: 'from-green-950',
        gradientTo: 'to-emerald-950',
        isPremium: true,
    },
    {
        name: 'Midnight Ocean',
        background: 'bg-blue-950',
        text: 'text-blue-100',
        primary: 'bg-cyan-500',
        primaryHover: 'bg-cyan-600',
        secondary: 'bg-teal-600',
        secondaryHover: 'bg-teal-700',
        cardBg: 'bg-blue-900',
        cardText: 'text-blue-200',
        border: 'border-blue-800',
        buttonPrimary: 'bg-cyan-500',
        buttonPrimaryHover: 'bg-cyan-600',
        buttonText: 'text-white',
        highlight: 'text-cyan-400',
        highlightSecondary: 'text-teal-400',
        highlightTertiary: 'text-sky-400',
        successColor: 'text-emerald-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-rose-400',
        infoColor: 'text-sky-400',
        iconBg: 'bg-cyan-500/10',
        gradientFrom: 'from-blue-950',
        gradientTo: 'to-cyan-950',
        isPremium: false,
    },
    {
        name: 'Charcoal Steel',
        background: 'bg-gray-950',
        text: 'text-gray-100',
        primary: 'bg-gray-500',
        primaryHover: 'bg-gray-400',
        secondary: 'bg-zinc-600',
        secondaryHover: 'bg-zinc-500',
        cardBg: 'bg-gray-900',
        cardText: 'text-gray-300',
        border: 'border-gray-700',
        buttonPrimary: 'bg-gray-500',
        buttonPrimaryHover: 'bg-gray-400',
        buttonText: 'text-white',
        highlight: 'text-gray-400',
        highlightSecondary: 'text-zinc-400',
        highlightTertiary: 'text-slate-400',
        successColor: 'text-green-400',
        warningColor: 'text-orange-400',
        errorColor: 'text-red-400',
        infoColor: 'text-blue-400',
        iconBg: 'bg-gray-500/10',
        gradientFrom: 'from-gray-950',
        gradientTo: 'to-black',
        isPremium: false,
    },
    {
        name: 'Neon Dreams',
        background: 'bg-black',
        text: 'text-gray-100',
        primary: 'bg-pink-600',
        primaryHover: 'bg-pink-700',
        secondary: 'bg-violet-600',
        secondaryHover: 'bg-violet-700',
        cardBg: 'bg-gray-900',
        cardText: 'text-gray-200',
        border: 'border-gray-800',
        buttonPrimary: 'bg-pink-600',
        buttonPrimaryHover: 'bg-pink-700',
        buttonText: 'text-white',
        highlight: 'text-pink-400',
        highlightSecondary: 'text-violet-400',
        highlightTertiary: 'text-fuchsia-400',
        successColor: 'text-lime-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-cyan-400',
        iconBg: 'bg-pink-600/10',
        gradientFrom: 'from-black',
        gradientTo: 'to-gray-900',
        isPremium: true,
    },
    {
        name: 'Cyberpunk',
        background: 'bg-gray-900',
        text: 'text-green-400',
        primary: 'bg-green-500',
        primaryHover: 'bg-green-400',
        secondary: 'bg-cyan-500',
        secondaryHover: 'bg-cyan-400',
        cardBg: 'bg-black',
        cardText: 'text-green-300',
        border: 'border-green-600',
        buttonPrimary: 'bg-green-500',
        buttonPrimaryHover: 'bg-green-400',
        buttonText: 'text-black',
        highlight: 'text-green-400',
        highlightSecondary: 'text-cyan-400',
        highlightTertiary: 'text-lime-400',
        successColor: 'text-lime-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-cyan-400',
        iconBg: 'bg-green-500/10',
        gradientFrom: 'from-gray-900',
        gradientTo: 'to-black',
        isPremium: true,
    },
    {
        name: 'Retro Sunset',
        background: 'bg-pink-900',
        text: 'text-pink-100',
        primary: 'bg-purple-500',
        primaryHover: 'bg-purple-400',
        secondary: 'bg-orange-500',
        secondaryHover: 'bg-orange-400',
        cardBg: 'bg-pink-800',
        cardText: 'text-pink-200',
        border: 'border-pink-600',
        buttonPrimary: 'bg-purple-500',
        buttonPrimaryHover: 'bg-purple-400',
        buttonText: 'text-white',
        highlight: 'text-purple-400',
        highlightSecondary: 'text-orange-400',
        highlightTertiary: 'text-yellow-400',
        successColor: 'text-lime-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-sky-400',
        iconBg: 'bg-purple-500/10',
        gradientFrom: 'from-pink-900',
        gradientTo: 'to-purple-900',
        isPremium: true,
    },
    // New premium themes below
    {
        name: 'Royal Gold',
        background: 'bg-yellow-950',
        text: 'text-yellow-100',
        primary: 'bg-yellow-600',
        primaryHover: 'bg-yellow-500',
        secondary: 'bg-amber-700',
        secondaryHover: 'bg-amber-600',
        cardBg: 'bg-yellow-900',
        cardText: 'text-yellow-200',
        border: 'border-yellow-800',
        buttonPrimary: 'bg-yellow-600',
        buttonPrimaryHover: 'bg-yellow-500',
        buttonText: 'text-yellow-950',
        highlight: 'text-yellow-400',
        highlightSecondary: 'text-amber-400',
        highlightTertiary: 'text-orange-400',
        successColor: 'text-emerald-400',
        warningColor: 'text-amber-400',
        errorColor: 'text-red-400',
        infoColor: 'text-blue-400',
        iconBg: 'bg-yellow-600/10',
        gradientFrom: 'from-yellow-950',
        gradientTo: 'to-amber-950',
        isPremium: true,
    },
    {
        name: 'Deep Space',
        background: 'bg-indigo-950',
        text: 'text-indigo-100',
        primary: 'bg-violet-600',
        primaryHover: 'bg-violet-500',
        secondary: 'bg-fuchsia-600',
        secondaryHover: 'bg-fuchsia-500',
        cardBg: 'bg-indigo-900',
        cardText: 'text-indigo-200',
        border: 'border-indigo-800',
        buttonPrimary: 'bg-violet-600',
        buttonPrimaryHover: 'bg-violet-500',
        buttonText: 'text-white',
        highlight: 'text-violet-400',
        highlightSecondary: 'text-fuchsia-400',
        highlightTertiary: 'text-pink-400',
        successColor: 'text-emerald-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-blue-400',
        iconBg: 'bg-violet-600/10',
        gradientFrom: 'from-indigo-950',
        gradientTo: 'to-violet-950',
        isPremium: true,
    },
    {
        name: 'Emerald Oasis',
        background: 'bg-emerald-950',
        text: 'text-emerald-100',
        primary: 'bg-teal-500',
        primaryHover: 'bg-teal-400',
        secondary: 'bg-cyan-500',
        secondaryHover: 'bg-cyan-400',
        cardBg: 'bg-emerald-900',
        cardText: 'text-emerald-200',
        border: 'border-emerald-800',
        buttonPrimary: 'bg-teal-500',
        buttonPrimaryHover: 'bg-teal-400',
        buttonText: 'text-emerald-950',
        highlight: 'text-teal-400',
        highlightSecondary: 'text-cyan-400',
        highlightTertiary: 'text-sky-400',
        successColor: 'text-lime-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-blue-400',
        iconBg: 'bg-teal-500/10',
        gradientFrom: 'from-emerald-950',
        gradientTo: 'to-teal-950',
        isPremium: true,
    },
    {
        name: 'Crimson Noir',
        background: 'bg-red-950',
        text: 'text-red-100',
        primary: 'bg-rose-600',
        primaryHover: 'bg-rose-500',
        secondary: 'bg-pink-600',
        secondaryHover: 'bg-pink-500',
        cardBg: 'bg-red-900',
        cardText: 'text-red-200',
        border: 'border-red-800',
        buttonPrimary: 'bg-rose-600',
        buttonPrimaryHover: 'bg-rose-500',
        buttonText: 'text-white',
        highlight: 'text-rose-400',
        highlightSecondary: 'text-pink-400',
        highlightTertiary: 'text-fuchsia-400',
        successColor: 'text-emerald-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-blue-400',
        iconBg: 'bg-rose-600/10',
        gradientFrom: 'from-red-950',
        gradientTo: 'to-rose-950',
        isPremium: true,
    },
    {
        name: 'Obsidian Luxe',
        background: 'bg-stone-950',
        text: 'text-stone-100',
        primary: 'bg-stone-600',
        primaryHover: 'bg-stone-500',
        secondary: 'bg-stone-700',
        secondaryHover: 'bg-stone-600',
        cardBg: 'bg-stone-900',
        cardText: 'text-stone-200',
        border: 'border-stone-800',
        buttonPrimary: 'bg-stone-600',
        buttonPrimaryHover: 'bg-stone-500',
        buttonText: 'text-white',
        highlight: 'text-stone-400',
        highlightSecondary: 'text-stone-300',
        highlightTertiary: 'text-stone-200',
        successColor: 'text-emerald-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-blue-400',
        iconBg: 'bg-stone-600/10',
        gradientFrom: 'from-stone-950',
        gradientTo: 'to-black',
        isPremium: true,
    },
    // Free themes continue below
    {
        name: 'Copper Bronze',
        background: 'bg-amber-950',
        text: 'text-amber-100',
        primary: 'bg-orange-600',
        primaryHover: 'bg-orange-700',
        secondary: 'bg-red-700',
        secondaryHover: 'bg-red-800',
        cardBg: 'bg-amber-900',
        cardText: 'text-amber-200',
        border: 'border-amber-800',
        buttonPrimary: 'bg-orange-600',
        buttonPrimaryHover: 'bg-orange-700',
        buttonText: 'text-white',
        highlight: 'text-orange-400',
        highlightSecondary: 'text-red-400',
        highlightTertiary: 'text-yellow-400',
        successColor: 'text-lime-400',
        warningColor: 'text-yellow-400',
        errorColor: 'text-red-400',
        infoColor: 'text-sky-400',
        iconBg: 'bg-orange-600/10',
        gradientFrom: 'from-amber-950',
        gradientTo: 'to-orange-950',
        isPremium: false,
    },
    {
        name: 'Sunny Meadow',
        background: 'bg-lime-50',
        text: 'text-lime-900',
        primary: 'bg-green-600',
        primaryHover: 'bg-green-700',
        secondary: 'bg-emerald-700',
        secondaryHover: 'bg-emerald-800',
        cardBg: 'bg-white',
        cardText: 'text-lime-800',
        border: 'border-lime-200',
        buttonPrimary: 'bg-green-600',
        buttonPrimaryHover: 'bg-green-700',
        buttonText: 'text-white',
        highlight: 'text-green-600',
        highlightSecondary: 'text-lime-700',
        highlightTertiary: 'text-emerald-700',
        successColor: 'text-lime-700',
        warningColor: 'text-amber-700',
        errorColor: 'text-red-700',
        infoColor: 'text-blue-700',
        iconBg: 'bg-green-600/10',
        gradientFrom: 'from-lime-50',
        gradientTo: 'to-emerald-50',
        isPremium: false,
    },
    {
        name: 'Arctic Blue',
        background: 'bg-blue-50',
        text: 'text-blue-900',
        primary: 'bg-cyan-600',
        primaryHover: 'bg-cyan-700',
        secondary: 'bg-blue-700',
        secondaryHover: 'bg-blue-800',
        cardBg: 'bg-white',
        cardText: 'text-blue-800',
        border: 'border-blue-200',
        buttonPrimary: 'bg-cyan-600',
        buttonPrimaryHover: 'bg-cyan-700',
        buttonText: 'text-white',
        highlight: 'text-cyan-600',
        highlightSecondary: 'text-blue-700',
        highlightTertiary: 'text-teal-600',
        successColor: 'text-emerald-700',
        warningColor: 'text-orange-700',
        errorColor: 'text-red-700',
        infoColor: 'text-sky-700',
        iconBg: 'bg-cyan-600/10',
        gradientFrom: 'from-blue-50',
        gradientTo: 'to-cyan-50',
        isPremium: false,
    },
    {
        name: 'Soft Clay',
        background: 'bg-stone-100',
        text: 'text-stone-800',
        primary: 'bg-emerald-600',
        primaryHover: 'bg-emerald-700',
        secondary: 'bg-teal-700',
        secondaryHover: 'bg-teal-800',
        cardBg: 'bg-white',
        cardText: 'text-stone-700',
        border: 'border-stone-200',
        buttonPrimary: 'bg-emerald-600',
        buttonPrimaryHover: 'bg-emerald-700',
        buttonText: 'text-white',
        highlight: 'text-emerald-600',
        highlightSecondary: 'text-teal-700',
        highlightTertiary: 'text-green-700',
        successColor: 'text-emerald-700',
        warningColor: 'text-amber-700',
        errorColor: 'text-red-700',
        infoColor: 'text-blue-700',
        iconBg: 'bg-emerald-600/10',
        gradientFrom: 'from-stone-100',
        gradientTo: 'to-amber-100',
        isPremium: false,
    },
    {
        name: 'Bubblegum Pop',
        background: 'bg-pink-50',
        text: 'text-pink-900',
        primary: 'bg-fuchsia-500',
        primaryHover: 'bg-fuchsia-600',
        secondary: 'bg-purple-600',
        secondaryHover: 'bg-purple-700',
        cardBg: 'bg-white',
        cardText: 'text-pink-800',
        border: 'border-pink-200',
        buttonPrimary: 'bg-fuchsia-500',
        buttonPrimaryHover: 'bg-fuchsia-600',
        buttonText: 'text-white',
        highlight: 'text-fuchsia-500',
        highlightSecondary: 'text-purple-600',
        highlightTertiary: 'text-rose-500',
        successColor: 'text-emerald-600',
        warningColor: 'text-amber-600',
        errorColor: 'text-red-600',
        infoColor: 'text-blue-600',
        iconBg: 'bg-fuchsia-500/10',
        gradientFrom: 'from-pink-50',
        gradientTo: 'to-rose-50',
        isPremium: false,
    },
    {
        name: 'Warm Clay',
        background: 'bg-orange-50',
        text: 'text-stone-900',
        primary: 'bg-amber-600',
        primaryHover: 'bg-amber-700',
        secondary: 'bg-red-500',
        secondaryHover: 'bg-red-600',
        cardBg: 'bg-white',
        cardText: 'text-stone-700',
        border: 'border-orange-200',
        buttonPrimary: 'bg-amber-600',
        buttonPrimaryHover: 'bg-amber-700',
        buttonText: 'text-white',
        highlight: 'text-amber-600',
        highlightSecondary: 'text-red-500',
        highlightTertiary: 'text-orange-500',
        successColor: 'text-emerald-600',
        warningColor: 'text-yellow-600',
        errorColor: 'text-red-600',
        infoColor: 'text-blue-600',
        iconBg: 'bg-amber-600/10',
        gradientFrom: 'from-orange-50',
        gradientTo: 'to-red-50',
        isPremium: false,
    },
    {
        name: 'Lavender Fields',
        background: 'bg-purple-50',
        text: 'text-purple-900',
        primary: 'bg-violet-600',
        primaryHover: 'bg-violet-700',
        secondary: 'bg-indigo-600',
        secondaryHover: 'bg-indigo-700',
        cardBg: 'bg-white',
        cardText: 'text-purple-800',
        border: 'border-purple-200',
        buttonPrimary: 'bg-violet-600',
        buttonPrimaryHover: 'bg-violet-700',
        buttonText: 'text-white',
        highlight: 'text-violet-600',
        highlightSecondary: 'text-indigo-600',
        highlightTertiary: 'text-purple-600',
        successColor: 'text-emerald-600',
        warningColor: 'text-amber-600',
        errorColor: 'text-red-600',
        infoColor: 'text-blue-600',
        iconBg: 'bg-violet-600/10',
        gradientFrom: 'from-purple-50',
        gradientTo: 'to-violet-50',
        isPremium: false,
    },
    {
        name: 'Mint Fresh',
        background: 'bg-emerald-50',
        text: 'text-emerald-900',
        primary: 'bg-teal-600',
        primaryHover: 'bg-teal-700',
        secondary: 'bg-green-600',
        secondaryHover: 'bg-green-700',
        cardBg: 'bg-white',
        cardText: 'text-emerald-800',
        border: 'border-emerald-200',
        buttonPrimary: 'bg-teal-600',
        buttonPrimaryHover: 'bg-teal-700',
        buttonText: 'text-white',
        highlight: 'text-teal-600',
        highlightSecondary: 'text-green-600',
        highlightTertiary: 'text-emerald-600',
        successColor: 'text-green-700',
        warningColor: 'text-orange-700',
        errorColor: 'text-red-700',
        infoColor: 'text-blue-700',
        iconBg: 'bg-teal-600/10',
        gradientFrom: 'from-emerald-50',
        gradientTo: 'to-teal-50',
        isPremium: false,
    },
    {
        name: 'Golden Hour',
        background: 'bg-yellow-50',
        text: 'text-yellow-900',
        primary: 'bg-amber-600',
        primaryHover: 'bg-amber-700',
        secondary: 'bg-orange-600',
        secondaryHover: 'bg-orange-700',
        cardBg: 'bg-white',
        cardText: 'text-yellow-800',
        border: 'border-yellow-200',
        buttonPrimary: 'bg-amber-600',
        buttonPrimaryHover: 'bg-amber-700',
        buttonText: 'text-white',
        highlight: 'text-amber-600',
        highlightSecondary: 'text-orange-600',
        highlightTertiary: 'text-yellow-600',
        successColor: 'text-emerald-600',
        warningColor: 'text-orange-600',
        errorColor: 'text-red-600',
        infoColor: 'text-blue-600',
        iconBg: 'bg-amber-600/10',
        gradientFrom: 'from-yellow-50',
        gradientTo: 'to-amber-50',
        isPremium: false,
    },
    {
        name: 'Rose Garden',
        background: 'bg-rose-50',
        text: 'text-rose-900',
        primary: 'bg-rose-600',
        primaryHover: 'bg-rose-700',
        secondary: 'bg-pink-600',
        secondaryHover: 'bg-pink-700',
        cardBg: 'bg-white',
        cardText: 'text-rose-800',
        border: 'border-rose-200',
        buttonPrimary: 'bg-rose-600',
        buttonPrimaryHover: 'bg-rose-700',
        buttonText: 'text-white',
        highlight: 'text-rose-600',
        highlightSecondary: 'text-pink-600',
        highlightTertiary: 'text-red-600',
        successColor: 'text-emerald-600',
        warningColor: 'text-amber-600',
        errorColor: 'text-red-600',
        infoColor: 'text-blue-600',
        iconBg: 'bg-rose-600/10',
        gradientFrom: 'from-rose-50',
        gradientTo: 'to-pink-50',
        isPremium: false,
    },
    {
        name: 'Cloud Nine',
        background: 'bg-gray-50',
        text: 'text-gray-900',
        primary: 'bg-slate-600',
        primaryHover: 'bg-slate-700',
        secondary: 'bg-gray-600',
        secondaryHover: 'bg-gray-700',
        cardBg: 'bg-white',
        cardText: 'text-gray-800',
        border: 'border-gray-200',
        buttonPrimary: 'bg-slate-600',
        buttonPrimaryHover: 'bg-slate-700',
        buttonText: 'text-white',
        highlight: 'text-slate-600',
        highlightSecondary: 'text-gray-600',
        highlightTertiary: 'text-zinc-600',
        successColor: 'text-emerald-600',
        warningColor: 'text-amber-600',
        errorColor: 'text-red-600',
        infoColor: 'text-blue-600',
        iconBg: 'bg-slate-600/10',
        gradientFrom: 'from-gray-50',
        gradientTo: 'to-slate-50',
        isPremium: false,
    },
    {
        name: 'Peachy Keen',
        background: 'bg-orange-50',
        text: 'text-orange-900',
        primary: 'bg-orange-500',
        primaryHover: 'bg-orange-600',
        secondary: 'bg-amber-500',
        secondaryHover: 'bg-amber-600',
        cardBg: 'bg-white',
        cardText: 'text-orange-800',
        border: 'border-orange-200',
        buttonPrimary: 'bg-orange-500',
        buttonPrimaryHover: 'bg-orange-600',
        buttonText: 'text-white',
        highlight: 'text-orange-500',
        highlightSecondary: 'text-amber-500',
        highlightTertiary: 'text-red-500',
        successColor: 'text-emerald-600',
        warningColor: 'text-yellow-600',
        errorColor: 'text-red-600',
        infoColor: 'text-blue-600',
        iconBg: 'bg-orange-500/10',
        gradientFrom: 'from-orange-50',
        gradientTo: 'to-amber-50',
        isPremium: false,
    },
    {
        name: 'Arctic Winter',
        background: 'bg-slate-50',
        text: 'text-slate-800',
        primary: 'bg-blue-500',
        primaryHover: 'bg-blue-600',
        secondary: 'bg-slate-500',
        secondaryHover: 'bg-slate-600',
        cardBg: 'bg-white',
        cardText: 'text-slate-700',
        border: 'border-slate-200',
        buttonPrimary: 'bg-blue-500',
        buttonPrimaryHover: 'bg-blue-600',
        buttonText: 'text-white',
        highlight: 'text-blue-500',
        highlightSecondary: 'text-slate-500',
        highlightTertiary: 'text-gray-500',
        successColor: 'text-emerald-600',
        warningColor: 'text-amber-600',
        errorColor: 'text-red-600',
        infoColor: 'text-blue-600',
        iconBg: 'bg-blue-500/10',
        gradientFrom: 'from-slate-50',
        gradientTo: 'to-blue-50',
        isPremium: false,
    }
];